###################################
#  Config File
#  
#  ver.1000
###################################

pluginenable: false
worldname: dungeon

###################################
# Plugin Settings
###################################

ENABLE_PLUGIN:
DUNGEON_GENERATE_WORLD:

###################################
# Dungeon Generate Trigger
###################################

ENABLE_DUNGEON_MOSSY:
ENABLE_DUNGEON_STRONGHORLD:
ENABLE_DUNGEON_VILLAGE:

###################################
# Messages
###################################

message:
  general:
    command-generate: ' has generating... '
    command-generate-error-null: ' You must specify a dungeon name. '
    command-generate-error-not: ' has not found dungeon. '
    command-generate-complate: ' has generate '
    command-generate-complate-2: ' dungeon complate. '
